services:
  mysqldb:
    image: mysql:8
    container_name: mysql-dbs
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: donationdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    platform: linux/amd64
    image: rishindravarmam/docker-backend:latest
    container_name: springboots
    ports:
      - "2026:7070"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    platform: linux/amd64
    image: rishindravarmam/docker-frontend:latest
    container_name: reacts
    ports:
      - "3001:70"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net: